insert into boat (id, name, description)
values  (1, 'Écureuil d''Aquitaine II', 'non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere'),
        (2, 'Lada Poch', 'lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus'),
        (3, '36.15 MET', 'dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum'),
        (4, 'Crédit Agricole IV', 'amet diam in magna bibendum imperdiet nullam orci pede venenatis non'),
        (5, 'TBS-Charente Maritime', 'eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum'),
        (6, 'Generali Concorde', 'dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut'),
        (7, 'Cacharel', 'fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis'),
        (8, 'Bagages Superior', 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse'),
        (9, 'Groupe Sofap-Helvim', 'tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla'),
        (10, 'Fleury Michon X', 'rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis'),
        (11, 'Cacolac d''Aquitaine', 'dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit'),
        (12, 'K&H Bank Matav', 'felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc'),
        (13, 'Euskadi Europ 93 BBK', 'hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci'),
        (14, 'PRB/Solo Nantes', 'orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin'),
        (15, 'Geodis', 'porttitor lacus at turpis donec posuere metus vitae ipsum aliquam'),
        (16, 'Crédit immobilier de France', 'in faucibus orci luctus et ultrices posuere cubilia curae mauris'),
        (17, 'Groupe LG-Traitmat', 'morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id'),
        (18, 'Café Legal-Le Goût', 'id luctus nec molestie sed justo pellentesque viverra pede ac diam'),
        (19, 'Aqua Quorum', 'platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent'),
        (20, 'Whirlpool-Europe 2', 'mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida'),
        (21, 'PRB', 'mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec'),
        (22, 'Kingfisher', 'elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor'),
        (23, 'Sill Matines La potagère', 'orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis'),
        (24, 'Active Wear', 'iaculis diam erat fermentum justo nec condimentum neque sapien placerat'),
        (25, 'Union bancaire privée', 'ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et'),
        (26, 'Sodebo', 'felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec'),
        (27, 'Team Group 4', 'dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh'),
        (28, 'Voila.fr', 'ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar'),
        (29, 'Gartmore', 'integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien'),
        (30, 'Nord-pas-de-Calais/chocolats du Monde', 'fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget'),
        (31, 'VM Matériaux', 'cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque'),
        (32, 'Aquarelle.com', 'pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam'),
        (33, 'Aquitaine Innovations', 'dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit'),
        (34, 'DDP/60e Sud', 'aenean fermentum donec ut mauris eget massa tempor convallis nulla neque'),
        (35, 'Wind Telecommunicazioni', 'mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta'),
        (36, 'Bonduelle', 'mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus'),
        (37, 'Ecover', 'neque libero convallis eget eleifend luctus ultricies eu nibh quisque'),
        (38, 'Temenos', 'erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero'),
        (39, 'VMI', 'non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at'),
        (40, 'Virbac-Paprec', 'turpis a pede posuere nonummy integer non velit donec diam neque'),
        (41, 'Hellomoto', 'rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo'),
        (42, 'Arcelor-Dunkerque', 'sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede'),
        (43, 'Ocean Planet', 'massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh'),
        (44, 'Max Havelaar/Best Western', 'nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim'),
        (45, 'Roxy', 'porttitor id consequat in consequat ut nulla sed accumsan felis'),
        (46, 'Akena Verandas', 'nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit'),
        (47, 'Benefic', 'leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit'),
        (48, 'Foncia', 'nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit'),
        (49, 'Brit Air', 'enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper'),
        (50, 'Safran', 'nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia'),
        (51, 'Bahrain Team Pindar', 'rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta'),
        (52, 'Aviva', 'nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat'),
        (53, 'Akena Vérandas', 'mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque'),
        (54, 'Toe In The Water', 'elit proin risus praesent lectus vestibulum quam sapien varius ut blandit'),
        (55, 'Great American III', 'congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis'),
        (56, 'Fondation Océan Vital', 'et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet'),
        (57, 'Nauticsport Kapsch', 'lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu'),
        (58, 'Macif', 'ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend'),
        (59, 'Banque populaire', 'tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim'),
        (60, 'Hugo Boss', 'integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in'),
        (61, 'Virbac-Paprec 3', 'in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque'),
        (62, 'SynerCiel', 'non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in'),
        (63, 'Gamesa', 'non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta'),
        (64, 'Mirabaud', 'leo maecenas pulvinar lobortis est phasellus sit amet erat nulla'),
        (65, 'Akena Vérandas', 'mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id'),
        (66, 'Votre Nom autour du Monde', 'sit amet eleifend pede libero quis orci nullam molestie nibh'),
        (67, 'Initiatives-Cœur', 'morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum'),
        (68, 'Team Plastique', 'ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor'),
        (69, 'Banque Populaire VIII', 'aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec'),
        (70, 'Hugo Boss', 'consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce'),
        (71, 'Maître Coq', 'pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus'),
        (72, 'StMichel-Virbac', 'sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac'),
        (73, 'Quéguiner - Leucémie Espoir', 'ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec'),
        (74, 'Finistère Mer Vent', 'platea dictumst maecenas ut massa quis augue luctus tincidunt nulla'),
        (75, 'Bureau Vallée', 'fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in'),
        (76, 'Spirit of Hungary', 'at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse'),
        (77, 'Comme un seul homme', 'ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec'),
        (78, 'La Mie câline', 'non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel'),
        (79, 'Newrest-Matmut', 'accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum'),
        (80, 'Armor-Lux/foies Gras', 'congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque'),
        (81, 'Great American IV', 'justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi'),
        (82, 'One planet One ocean', 'ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo'),
        (83, 'Famille Mary - Étamine du Lys', 'mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus'),
        (84, '100% Natural Energy', 'sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec'),
        (85, 'No Way Back', 'pellentesque quisque porta volutpat erat quisque erat eros viverra eget'),
        (86, 'TechnoFirst-FaceOcean', 'quisque arcu libero rutrum ac lobortis vel dapibus at diam'),
        (87, 'Le Souffle du Nord Team Ireland', 'eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor'),
        (88, 'Bureau Vallée 2', 'etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus'),
        (89, 'Yes we Cam!', 'dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia'),
        (90, 'Seaexplorer-Yacht', 'aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero'),
        (91, 'Club De Monaco', 'quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis'),
        (92, 'LinkedOut', 'placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet'),
        (93, 'Groupe APICIL', 'donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id'),
        (94, 'Prysmian Group', 'ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel'),
        (95, 'OMIA - Water Family', 'eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et'),
        (96, 'V And B Mayenne', 'cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae'),
        (97, 'L''Occitane en Provence', 'tortor id nulla ultrices aliquet maecenas leo odio condimentum id'),
        (98, 'Banque Populaire X', 'vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet'),
        (99, 'Charal', 'scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc'),
        (100, 'Pure - Best Western', 'diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque'),
        (102, 'Artisans Artipole', 'ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar'),
        (103, 'DMG Mori', 'integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien'),
        (104, 'La Fabrique', 'fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget'),
        (105, 'Time For Oceans', 'cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque'),
        (106, 'Medallia', 'pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam'),
        (107, 'One Ocean One Planet', 'dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit'),
        (108, 'Compagnie du Lit Jiliti', 'aenean fermentum donec ut mauris eget massa tempor convallis nulla neque'),
        (109, 'Campagne de France', 'mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta'),
        (110, 'Groupe Setin', 'mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus'),
        (111, 'TSE - 4MyPlanet', 'dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh'),
        (112, 'Stark', 'ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar');