spring:
  datasource:
    username: root
    password: boat-app-db-password
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boat-db
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
  hateoas:
    use-hal-as-default-json-media-type: false
  jpa:
    hibernate:
      ddl-auto: validate
  security:
    user:
      password: password
